/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author João Victor
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtconfirmesenha = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txtdatanascimento = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        getContentPane().setLayout(null);

        jLabel1.setText("Bem vindo(a)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 60, 100, 15);

        jLabel2.setText("Nome do usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 170, 110, 15);

        jLabel3.setText("CPF");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 210, 40, 15);

        jLabel4.setText("Data de nascimento");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 250, 120, 15);

        jLabel5.setText("Cargo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 290, 60, 15);

        jLabel6.setText("Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 330, 60, 15);

        jLabel7.setText("Confirme a senha");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 360, 110, 15);
        getContentPane().add(txtconfirmesenha);
        txtconfirmesenha.setBounds(250, 360, 240, 30);
        getContentPane().add(txtnome);
        txtnome.setBounds(250, 160, 230, 30);
        getContentPane().add(txtcpf);
        txtcpf.setBounds(250, 200, 230, 30);
        getContentPane().add(txtdatanascimento);
        txtdatanascimento.setBounds(250, 240, 160, 30);
        getContentPane().add(txtcargo);
        txtcargo.setBounds(250, 280, 190, 30);
        getContentPane().add(txtsenha);
        txtsenha.setBounds(250, 320, 240, 30);

        jButton1.setText("Cadastre-se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(560, 430, 170, 60);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 430, 170, 60);

        setSize(new java.awt.Dimension(934, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtnome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"O nome é obrigatório");
            txtnome.requestFocus();
            return;
        }
        if(txtcpf.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "O cpf é obrigatório");
            txtcpf.requestFocus();
            return;
        }
        if(txtdatanascimento.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "A data de nascimento é obrigatória");
            txtdatanascimento.requestFocus();
            return;
        }
        if(txtcargo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "o cargo é obrigatório");
            txtcargo.requestFocus();
            return;
        }
        if(txtsenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "a senha é obrigatória");
            txtsenha.requestFocus();
            return;
        }
        if(Integer.parseInt(txtsenha.getText())!= Integer.parseInt(txtconfirmesenha.getText())){
            JOptionPane.showMessageDialog(null, "As senhas estão diferentes");
            txtsenha.requestFocus();
            return;
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                Connection conect = DriverManager.getConnection("jdbc:mysql://localhost:3306/projeto", "root", "jv982314");
                PreparedStatement st = conect.prepareStatement("insert into usuario_projeto values (?,?,?,?,?)");
                st.setString(1, txtnome.getText());
                st.setString(2, txtcpf.getText());
                st.setString(3, txtdatanascimento.getText());
                st.setString(4, txtcargo.getText());
                st.setString(5, txtsenha.getText());
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "usuario cadastrado com sucesso");
            } catch (SQLException ex) {
                Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           new Inicio().setVisible(true);
           dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtconfirmesenha;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtdatanascimento;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtsenha;
    // End of variables declaration//GEN-END:variables
}
